const products = [
    {
      '_id': '1',
      'name': 'Skateboard Bolts',
      'image': '/images/bolts.jpg',
      'description': '1" M6 skateboard bolts',
      'brand': 'Freedom Forged',
      'category': 'Hardware',
      'price': 9.99,
      'countInStock': 0,
      'rating': 5,
      'numReviews': 120,
    },
    {
      '_id': '2',
      'name': 'Skateboard Wax',
      'image': '/images/wax.jpg',
      'description': 'Skateboard wax apply to any surface for G level 50-50',
      'brand': 'Freedom Forged',
      'category': 'Hardware',
      'price': 7.99,
      'countInStock': 100,
      'rating': 1.5,
      'numReviews': 60,
    },
    {
      '_id': '3',
      'name': 'T-Shirt',
      'image': '/images/tshirt.jpg',
      'description': 'A dope shirt, so dope it comes pre-laced with the sent of DOPE',
      'brand': 'Freedom Forged',
      'category': 'Apparel',
      'price': 29.99,
      'countInStock': 50,
      'rating': 5,
      'numReviews': 26,
    },
    {
      '_id': '4',
      'name': 'Hoodie',
      'image': '/images/hoodie.jpg',
      'description': 'A hoodie which will give you the power to intimidate almost anyone...',
      'brand': 'Freedom Forged',
      'category': 'Apparel',
      'price': 39.99,
      'countInStock': 50,
      'rating': 2.5,
      'numReviews': 15,
    },
    {
      '_id': '5',
      'name': 'Trainers',
      'image': '/images/trainers.jpg',
      'description': 'Trainers which look fresh, but they also improve stamina by >8x, do with that what you will?',
      'brand': 'Freedom Forged',
      'category': 'Apparel',
      'price': 49.99,
      'countInStock': 50,
      'rating': 4,
      'numReviews': 15,
    },
    {
      '_id': '6',
      'name': 'Poster',
      'image': '/images/poster.jpg',
      'description': 'Wicked & Bad...',
      'brand': 'Freedom Forged',
      'category': 'Apparel',
      'price': 49.99,
      'countInStock': 50,
      'rating': 3,
      'numReviews': 15,
    },
  ];

  export default products;